apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
data:
  color: red
  taste: sweet
---
apiVersion: v1
kind: Pod
metadata:
  name: demo
spec:
  containers:
  - name: nginx
    image: nginx:1.21.6-alpine
    env:
    - name: COLOR_PARAMETER
      valueFrom:
        configMapKeyRef:
          name: demo-config
          key: color
    - name: TASTE_PARAMETER
      valueFrom:
        configMapKeyRef:
          name: demo-config
          key: taste
