apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
data:
  COLOR_PARAMETER: red
  TASTE_PARAMETER: sweet
---
apiVersion: v1
kind: Pod
metadata:
  name: demo
spec:
  containers:
  - name: nginx
    image: nginx:1.21.6-alpine
    envFrom:
    - configMapRef:
        name: demo-config
