apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
data:
  sample.txt: |
    # Sample file contents
    parameter1 = value1
    parameter2 = value2
---
apiVersion: v1
kind: Pod
metadata:
  name: demo
spec:
  containers:
  - name: nginx
    image: nginx:1.21.6-alpine
    volumeMounts:
    - name: config-volume
      mountPath: /etc/
      subPath: sample.txt
  volumes:
  - name: config-volume
    configMap:
      name: demo-config
