apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: greetings.hy548.csd.uoc.gr
spec:
  group: hy548.csd.uoc.gr
  scope: Namespaced
  names:
    kind: Greeting
    listKind: GreetingList
    plural: greetings
    singular: greeting
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                message:
                  type: string
                replicas:
                  type: integer
                  minimum: 1
  preserveUnknownFields: false
